# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoFile/CaseFlame.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protoFile/CaseFlame.proto\"+\n\rListCaseFlame\x12\x1a\n\x06\x66lames\x18\x01 \x03(\x0b\x32\n.CaseFlame\"6\n\tCaseFlame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x17\n\x05\x66lame\x18\x02 \x01(\x0b\x32\x08.SubData\"\x90\x01\n\x07SubData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04self\x18\x03 \x01(\x05\x12\r\n\x05\x63\x61lls\x18\x04 \x01(\x05\x12\x0f\n\x07gcalloc\x18\x05 \x01(\x05\x12\x0e\n\x06timems\x18\x06 \x01(\x05\x12\x0e\n\x06selfms\x18\x07 \x01(\x05\x12\x1a\n\x08\x63hildren\x18\x08 \x03(\x0b\x32\x08.SubDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoFile.CaseFlame_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTCASEFLAME']._serialized_start=29
  _globals['_LISTCASEFLAME']._serialized_end=72
  _globals['_CASEFLAME']._serialized_start=74
  _globals['_CASEFLAME']._serialized_end=128
  _globals['_SUBDATA']._serialized_start=131
  _globals['_SUBDATA']._serialized_end=275
# @@protoc_insertion_point(module_scope)
